//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibNumberWeb
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class PhotoAlbum
    {
        public PhotoAlbum()
        {
            this.Photos = new HashSet<Photo>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage = "Url is required")]
        public string Url { get; set; }
        public string Name { get; set; }
        public int DetectionProgress { get; set; }
    
        [JsonIgnore]
        public virtual ICollection<Photo> Photos { get; set; }
    }
}
